const companies = [
    {
      id: 1,
      name: "Tech Innovators Inc.",
      industry: "Technology",
      location: "San Francisco, CA",
      employeeCount: 250,
      foundedYear: 2010,
    },
    {
      id: 2,
      name: "Green Future Solutions",
      industry: "Renewable Energy",
      location: "Austin, TX",
      employeeCount: 120,
      foundedYear: 2015,
    },
    {
      id: 3,
      name: "HealthFirst Corp.",
      industry: "Healthcare",
      location: "New York, NY",
      employeeCount: 500,
      foundedYear: 2000,
    },
    {
      id: 4,
      name: "EduWorld Ltd.",
      industry: "Education",
      location: "Boston, MA",
      employeeCount: 80,
      foundedYear: 2018,
    },
    {
      id: 5,
      name: "FinSecure Partners",
      industry: "Finance",
      location: "Chicago, IL",
      employeeCount: 300,
      foundedYear: 1995,
    },
    {
      id: 6,
      name: "BrightRetail Co.",
      industry: "Retail",
      location: "Seattle, WA",
      employeeCount: 150,
      foundedYear: 2012,
    },
    {
      id: 7,
      name: "EcoManufacturing Ltd.",
      industry: "Manufacturing",
      location: "Detroit, MI",
      employeeCount: 400,
      foundedYear: 1990,
    },
    {
      id: 8,
      name: "NextGen Transport",
      industry: "Transportation",
      location: "Dallas, TX",
      employeeCount: 220,
      foundedYear: 2005,
    },
    {
      id: 9,
      name: "SolarTech Solutions",
      industry: "Renewable Energy",
      location: "Phoenix, AZ",
      employeeCount: 180,
      foundedYear: 2017,
    },
    {
      id: 10,
      name: "MediCare Plus",
      industry: "Healthcare",
      location: "Los Angeles, CA",
      employeeCount: 350,
      foundedYear: 1998,
    },
    {
      id: 11,
      name: "EduTech Innovations",
      industry: "Education",
      location: "Palo Alto, CA",
      employeeCount: 90,
      foundedYear: 2020,
    },
    {
      id: 12,
      name: "SafeBanking Corp.",
      industry: "Finance",
      location: "Atlanta, GA",
      employeeCount: 500,
      foundedYear: 1985,
    },
    {
      id: 13,
      name: "UrbanStyle Retailers",
      industry: "Retail",
      location: "Portland, OR",
      employeeCount: 200,
      foundedYear: 2011,
    },
    {
      id: 14,
      name: "GreenEnergy Systems",
      industry: "Renewable Energy",
      location: "Denver, CO",
      employeeCount: 300,
      foundedYear: 2016,
    },
    {
      id: 15,
      name: "TechPioneers LLC",
      industry: "Technology",
      location: "San Jose, CA",
      employeeCount: 600,
      foundedYear: 2008,
    },
];

export default companies;